name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Check dependencies cache
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
            ./.next/cache
            ./.buildcache
            ./.eslintcache
          key: ${{ runner.os }}-deps-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/package-lock.json') }}

      - name: Maybe install dependencies
        run: |
          if [ ! -d node_modules ];
          then
            npm ci --loglevel warn --yes;
          else
            echo package.json and package-lock.json unchanged. Using cache.;
          fi

      - name: Lint
        run: npm run lint

      - name: Format check
        run: npm run check:format

      - name: Type check
        run: npm run check:types

      - name: Test
        run: npm run test:coverage

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: npm run build
