name: CI

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Check dependencies cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-deps-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: |
          if [ ! -d node_modules ];
          then
            npm ci --loglevel warn --yes;
          else
            echo package.json and package-lock.json unchanged. Using cache.;
          fi

  test:
    runs-on: ubuntu-latest
    needs: install

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Check dependencies cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-deps-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/package-lock.json') }}

      - name: Lint
        run: npm run lint

      - name: Format check
        run: npm run check:format

      - name: Type check
        run: npm run check:types

      - name: Test
        run: npm run test:coverage

      - name: Report coverage
        uses: coverallsapp/github-action@master
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}]

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Check dependencies cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-deps-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/package-lock.json') }}

      - name: Check next build cache
        uses: actions/cache@v2
        with:
          path: .next/cache
          key: ${{ runner.os }}-build-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/package-lock.json') }}

      - name: Build
        run: npm run build

      - name: Deploy branch
        uses: FirebaseExtended/action-hosting-deploy@v0
        if: github.ref != 'refs/heads/main'
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SEQUELIZE_UI_TS }}"
          projectId: sequelize-ui-ts
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

      - name: Deploy main
        uses: FirebaseExtended/action-hosting-deploy@v0
        if: github.ref == 'refs/heads/main'
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SEQUELIZE_UI_TS }}"
          channelId: live
          projectId: sequelize-ui-ts
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
