name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Check dependencies cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-deps-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: |
          if [ ! -d node_modules ];
          then
            npm ci --loglevel warn --yes;
          else
            echo package.json and package-lock.json unchanged. Using cache.;
          fi

      - name: Test
        run: npm run test:coverage

      - name: Report coverage
        uses: coverallsapp/github-action@master
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}]
